// Real data for MASID, generated by pipeline/build_dataset.py.
//
// Nothing in this module is invented. Every field traces to one of the sources
// listed in meta.json; anything the public record does not publish is absent
// here rather than filled in. See SOURCES.md.

import projectsRaw from "./projects.json";
import contractorsRaw from "./contractors.json";
import boundariesRaw from "./boundaries.json";
import satelliteRaw from "./satellite.json";
import procurementRaw from "./procurement.json";
import hazardRaw from "./hazard.json";
import metaRaw from "./meta.json";

/** Lifecycle stage only. "Flagged" is deliberately absent: it is a condition a
 *  contract can carry at any stage, and putting it here hid 245 completed
 *  contracts from the completed count. Use `auditFlags.length` for that. */
export type ProjectStatus = "completed" | "ongoing" | "proposed" | "terminated";
export type FlagSeverity = "high" | "medium" | "low";

export interface AuditFlag {
  code: string;
  severity: FlagSeverity;
  detail: string;
}

export interface Project {
  id: string;                       // DPWH contract ID
  name: string;
  description: string;
  contractor: string;
  municipality: string;
  declaredMunicipality: string | null;   // parsed from the contract description
  geocodedMunicipality: string | null;   // reverse-geocoded from published lat/lng
  offsetMetres: number | null;
  budget: number;
  amountPaid: number;
  status: ProjectStatus;
  dpwhStatus: string;               // DPWH's own status string, never overwritten
  completion: number;
  startDate: string | null;
  endDate: string | null;
  infraYear: number | null;
  lat: number | null;
  lng: number | null;
  fundingSource: string;
  districtOffice: string;
  hasSatelliteImage: boolean;
  reportCount: number;
  auditFlags: AuditFlag[];
  auditScore: number;
}

export interface Contractor {
  id: string;
  name: string;
  totalProjects: number;
  activeProjects: number;
  completedProjects: number;
  flaggedProjects: number;
  flagRate: number;
  totalValue: number;
  municipalities: string[];
  years: number[];
  registrationRevoked: boolean;
}

export interface Meta {
  generated: string;
  areaOfInterest: string;
  coverage: {
    projects: number;
    contractors: number;
    yearMin: number | null;
    yearMax: number | null;
    totalBudget: number;
    withCoordinates: number;
    flagged: number;
    municipalitiesServed: string[];
  };
  flagTally: Record<string, number>;
  sources: { name: string; publisher: string; url: string; license: string; provides: string }[];
  knownGaps: string[];
}

export const PROJECTS = projectsRaw as Project[];
export const CONTRACTORS = contractorsRaw as Contractor[];
export const META = metaRaw as Meta;

// ─── Flag reference ───────────────────────────────────────────────────────────
// Every check is a consistency test on published records. None of them observe
// the ground, and none of them assert that a project was not built.

export const FLAG_LABELS: Record<string, string> = {
  MISSING_COORDS: "No coordinates published",
  MUNI_MISMATCH: "Coordinate contradicts description",
  OUTSIDE_PROVINCE: "Coordinate outside Bulacan",
  UNLOCATABLE_COORD: "Coordinate outside all boundaries",
  OUTSIDE_DEO_AREA: "Outside district service area",
  COORD_DUPLICATE: "Coordinate shared with other contracts",
  CONTRACTOR_REVOKED: "Contractor registration marked revoked",
  BOUNDARY_ADJACENT: "Near municipal boundary",
  STATUS_PROGRESS_CONFLICT: "Status contradicts progress",
  DATE_ANOMALY: "Completion precedes start",
};

export const STATUS_LABELS: Record<ProjectStatus, string> = {
  completed: "Completed", ongoing: "Ongoing", flagged: "Flagged for review",
  proposed: "Proposed", terminated: "Terminated",
};

export const SEVERITY_CFG: Record<FlagSeverity, { label: string; color: string; bg: string }> = {
  high: { label: "High", color: "#b91c1c", bg: "#fee2e2" },
  medium: { label: "Medium", color: "#b45309", bg: "#fef3c7" },
  low: { label: "Low", color: "#0369a1", bg: "#e0f2fe" },
};

// ─── Derived aggregates ───────────────────────────────────────────────────────

const STATUS_KEYS: ProjectStatus[] = ["completed", "ongoing", "proposed", "terminated"];

/** Per-municipality status counts, busiest first. */
export const MUNI_BREAKDOWN = (() => {
  const rows = new Map<string, Record<string, number>>();
  for (const p of PROJECTS) {
    const key = p.municipality;
    if (!rows.has(key)) {
      rows.set(key, { name: key as unknown as number, ...Object.fromEntries(STATUS_KEYS.map(s => [s, 0])) } as never);
    }
    const row = rows.get(key)!;
    row[p.status] = (row[p.status] ?? 0) + 1;
  }
  return [...rows.values()]
    .map(r => ({ ...r, total: STATUS_KEYS.reduce((s, k) => s + (r[k] ?? 0), 0) }))
    .sort((a, b) => b.total - a.total)
    .slice(0, 12) as unknown as ({ name: string; total: number } & Record<ProjectStatus, number>)[];
})();

export const STATUS_PIE = (
  [
    { name: "Completed", key: "completed", color: "#16a34a" },
    { name: "Ongoing", key: "ongoing", color: "#2563eb" },
    { name: "Proposed", key: "proposed", color: "#94a3b8" },
    { name: "Terminated", key: "terminated", color: "#dc2626" },
  ] as const
)
  .map(s => ({ name: s.name, color: s.color, value: PROJECTS.filter(p => p.status === s.key).length }))
  .filter(s => s.value > 0);

/**
 * Contract value committed per infrastructure year, split by whether the record
 * carries an audit flag. There is no disbursement series: `amountPaid` is zero
 * on every completed record in this slice, so the portal simply does not
 * publish it. An invented one would be the whole problem in miniature.
 */
export const BUDGET_BY_YEAR = (() => {
  const years = new Map<number, { year: string; clean: number; flagged: number }>();
  for (const p of PROJECTS) {
    if (p.infraYear == null) continue;
    if (!years.has(p.infraYear)) years.set(p.infraYear, { year: String(p.infraYear), clean: 0, flagged: 0 });
    const row = years.get(p.infraYear)!;
    const millions = p.budget / 1_000_000;
    if (p.auditFlags.length) row.flagged += millions;
    else row.clean += millions;
  }
  return [...years.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([, v]) => ({ ...v, clean: Math.round(v.clean), flagged: Math.round(v.flagged) }));
})();

/** How many records tripped each check, most common first. */
export const FLAG_BREAKDOWN = Object.entries(META.flagTally)
  .map(([code, count]) => ({ code, label: FLAG_LABELS[code] ?? code, count }))
  .sort((a, b) => b.count - a.count);

export const FLAGGED_VALUE = PROJECTS
  .filter(p => p.auditFlags.length)
  .reduce((s, p) => s + p.budget, 0);

/** Real Bulacan municipal outlines (geoBoundaries ADM3), simplified for the canvas. */
export interface Boundary { name: string; rings: [number, number][][] }
export const BOUNDARIES = boundariesRaw as unknown as Boundary[];

/**
 * Map extent fitted to the province itself, not to the point cloud. Fitting to
 * the points would let a single malformed coordinate — the very thing this tool
 * exists to surface — zoom the whole map out to hide everything else.
 */
export const MAP_BOUNDS = (() => {
  const lats: number[] = [];
  const lngs: number[] = [];
  for (const b of BOUNDARIES) for (const ring of b.rings) for (const [x, y] of ring) { lngs.push(x); lats.push(y); }
  const pad = 0.02;
  return {
    minLat: Math.min(...lats) - pad,
    maxLat: Math.max(...lats) + pad,
    minLng: Math.min(...lngs) - pad,
    maxLng: Math.max(...lngs) + pad,
  };
})();

// ─── Satellite tier ───────────────────────────────────────────────────────────
// Sentinel-2 L2A change detection, generated by pipeline/satellite.py. Runs on an
// audit-priority subset plus a seeded control sample, so coverage is partial by
// design and every consumer has to handle "not assessed" as a first-class state.

export type Verdict = "change-at-point" | "change-offset" | "no-change-signal" | "not-assessable";

export interface RingReading {
  dNdvi: number; zNdvi: number; pctNdvi: number;
  dNdbi: number; zNdbi: number; pctNdbi: number;
  nullDiscs: number;
}

export interface SatelliteResult {
  id: string;
  /** NDVI chips with the sampling radii drawn on, served from /public/chips. */
  chips: { before: string; after: string } | null;
  verdict: Verdict;
  detail: string;
  confidence: "high" | "medium" | "low" | "none";
  rings: Record<string, RingReading | null>;
  control: { nullDiscs: number } | null;
  cloudFreeFraction: number;
  scenesBefore: string[];
  scenesAfter: string[];
  flagged: boolean;
}

export interface Validation {
  flagged: { assessed: number; detections: number; rate: number | null; medianZNdvi30m: number | null };
  control: { assessed: number; detections: number; rate: number | null; medianZNdvi30m: number | null };
  discriminates: boolean;
  verdict: string;
}

export interface SatelliteRun {
  generated: string;
  validation: Validation;
  source: { name: string; access: string; url: string; auth: string; resolution: string };
  method: Record<string, unknown>;
  coverage: { assessed: number; selected: number; assessable: number; total: number; skipped: Record<string, number> };
  results: SatelliteResult[];
}

export const SATELLITE = satelliteRaw as unknown as SatelliteRun;
export const VALIDATION = SATELLITE.validation;
export const SAT_BY_ID = new Map(SATELLITE.results.map(r => [r.id, r]));

/**
 * Wording matters more here than anywhere else in the app. "No change signal" is
 * not "not built" — a 10 m sensor cannot resolve a narrow revetment, and these
 * labels get read by people who can refer a contractor for prosecution.
 */
export const VERDICT_CFG: Record<Verdict, { label: string; short: string; color: string; bg: string; note: string }> = {
  "change-at-point": {
    label: "Change consistent with construction, at the coordinate",
    short: "Change at point",
    color: "#15803d", bg: "#dcfce7",
    note: "Something was built where the contract says it was built. Read with the validation result: controls detect at the same rate, so a single detection is not by itself informative.",
  },
  "change-offset": {
    label: "Change consistent with construction, offset from the coordinate",
    short: "Change offset",
    color: "#b45309", bg: "#fef3c7",
    note: "Construction appears near, but not at, the published coordinate — the displacement pattern.",
  },
  "no-change-signal": {
    label: "No change signal above local variation",
    short: "No signal",
    color: "#b91c1c", bg: "#fee2e2",
    note: "Nothing detectable at 10 m. NOT evidence of absence — and on this run the detector showed no measured ability to tell flagged records from controls, so this verdict carries no evidential weight about the contract.",
  },
  "not-assessable": {
    label: "Not assessable",
    short: "Not assessable",
    color: "#64748b", bg: "#f1f5f9",
    note: "Cloud cover or missing imagery leaves too little clear ground to compare the two periods.",
  },
};

export const SAT_TALLY = (() => {
  const t: Record<string, number> = {};
  for (const r of SATELLITE.results) t[r.verdict] = (t[r.verdict] ?? 0) + 1;
  return t;
})();

/** Points that fall outside the drawn extent — off-canvas, so counted instead. */
export const OFF_MAP = PROJECTS.filter(p =>
  p.lat != null && p.lng != null &&
  (p.lat < MAP_BOUNDS.minLat || p.lat > MAP_BOUNDS.maxLat ||
   p.lng < MAP_BOUNDS.minLng || p.lng > MAP_BOUNDS.maxLng)
);


// ─── Procurement tier ─────────────────────────────────────────────────────────
// From the DPWH full detail export (dpwh_transparency_data_all_details.parquet),
// not from PhilGEPS. Bidders, approved budget and the procurement timeline are
// all published there at 100% coverage — an earlier version of this app read the
// flat 24 MB export instead and wrongly documented them as unavailable.
//
// The data passes pipeline/verify_data.py before any of this is generated:
// the two BetterGov exports agree on every shared field, awards never exceed the
// approved budget, the procurement timeline is correctly ordered, and a sampled
// Notice of Award PDF matched its row to the centavo.

export interface ProcurementFlag {
  code: string;
  severity: FlagSeverity;
  detail: string;
  concentrationMultiple?: number;
  ratio?: number;
}

export interface ContractDocuments {
  advertisement: string | null;
  contractAgreement: string | null;
  noticeOfAward: string | null;
  noticeToProceed: string | null;
  programOfWork: string | null;
  engineeringDesign: string | null;
}

export interface ProcurementResult {
  id: string;
  bidders: number;
  winnerPcab: string | null;
  abc: number | null;
  awardAmount: number | null;
  bidRatio: number | null;
  bidWindowDays: number | null;
  advertisementDate: string | null;
  dateOfAward: string | null;
  valueShare: number | null;
  documents: ContractDocuments;
  procurementFlags: ProcurementFlag[];
  procurementScore: number;
}

export interface ProcurementRun {
  generated: string;
  districtOffice: string;
  source: { name: string; dataset: string; file: string; url: string; license: string; rowsUpstream: number };
  office: {
    contractsAllCategories: number; contractors: number; equalSplitShare: number;
    at96Rate: number; deoRankAt96: number; deosCompared: number;
    bidWindowP5Days: number; documentsPublished: number;
  };
  nationalBaseline: {
    contracts: number; wholePercentRate: number; at96Rate: number;
    singleBidderRate: number; medianRatio: number;
  };
  flagTally: Record<string, number>;
  results: ProcurementResult[];
}

export const PROCUREMENT = procurementRaw as unknown as ProcurementRun;
export const PROC_BY_ID = new Map(PROCUREMENT.results.map(r => [r.id, r]));

export const PROC_FLAG_LABELS: Record<string, string> = {
  BID_AT_ROUND_PERCENT: "Bid is a whole percentage of the approved budget",
  AWARD_CONCENTRATION: "Contractor concentration at this office",
  SINGLE_BIDDER: "Single bidder",
  TWO_BIDDERS: "Only two bidders",
  SHORT_BID_WINDOW: "Short bid window",
  NO_DOCUMENTS_PUBLISHED: "No contract documents published",
};

export const DOC_LABELS: Record<keyof ContractDocuments, string> = {
  advertisement: "Invitation to bid, BOQ and plans",
  contractAgreement: "Contract agreement",
  noticeOfAward: "Notice of award",
  noticeToProceed: "Notice to proceed",
  programOfWork: "Program of work",
  engineeringDesign: "Engineering design",
};

// ─── Fusion ───────────────────────────────────────────────────────────────────

const RECORDS_SUSPICIOUS = 3;      // one high-severity consistency check
const PROC_SUSPICIOUS = 3;         // e.g. a round-percentage bid plus thin competition

export type Quadrant = "both" | "records-only" | "procurement-only" | "neither";

export interface Fused {
  id: string;
  recordsScore: number;
  procurementScore: number;
  quadrant: Quadrant;
  budget: number;
}

/**
 * The 2x2 triage FUSION.md asks for, over every contract.
 *
 * Fusing is only worth doing if the two signals are independent, and they
 * measurably are: across all 1,293 contracts the records score and the
 * procurement score correlate at r = +0.05. Neither is a proxy for the other,
 * so "high on both" is genuinely narrower than either list alone.
 *
 * This is an ORDERING, not a prediction. There is no public itemised list of
 * confirmed ghost projects to validate against — the ICI turned its findings
 * over to the DOJ and Ombudsman rather than publishing them — so nothing here
 * has been shown to rank confirmed cases highly. It ranks contracts by how much
 * the public record disagrees with itself, which is a triage aid, not a verdict.
 */
export const FUSED: Fused[] = PROJECTS.map(p => {
  const proc = PROC_BY_ID.get(p.id);
  const ps = proc?.procurementScore ?? 0;
  const rs = p.auditScore;
  const hiR = rs >= RECORDS_SUSPICIOUS;
  const hiP = ps >= PROC_SUSPICIOUS;
  return {
    id: p.id,
    recordsScore: rs,
    procurementScore: ps,
    budget: p.budget,
    quadrant: (hiR && hiP ? "both" : hiR ? "records-only"
      : hiP ? "procurement-only" : "neither") as Quadrant,
  };
});

export const FUSED_BY_ID = new Map(FUSED.map(f => [f.id, f]));

export const QUADRANT_CFG: Record<Quadrant, { label: string; short: string; color: string; bg: string; note: string }> = {
  "both": {
    label: "Records and procurement both flag it", short: "Both",
    color: "#b91c1c", bg: "#fee2e2",
    note: "The contract record disagrees with itself AND the bidding shows a red flag — a whole-percentage bid, thin competition, or a heavily concentrated contractor. Two independent signals, so this is where inspection effort goes first.",
  },
  "records-only": {
    label: "Contract record only", short: "Records",
    color: "#b45309", bg: "#fef3c7",
    note: "The published record is internally inconsistent, but nothing stands out on the procurement side.",
  },
  "procurement-only": {
    label: "Procurement only", short: "Procurement",
    color: "#0369a1", bg: "#e0f2fe",
    note: "The bidding shows a red flag, but the contract record itself is consistent.",
  },
  "neither": {
    label: "Neither signal", short: "Neither",
    color: "#64748b", bg: "#f1f5f9",
    note: "Nothing flagged. Given how much the public record omits, this means 'nothing visible here', not 'clean'.",
  },
};

export const TRIAGE = (() => {
  const counts: Record<Quadrant, number> = { both: 0, "records-only": 0, "procurement-only": 0, neither: 0 };
  const value: Record<Quadrant, number> = { both: 0, "records-only": 0, "procurement-only": 0, neither: 0 };
  for (const f of FUSED) { counts[f.quadrant]++; value[f.quadrant] += f.budget; }
  return { counts, value };
})();

/** The "investigate first" list: both signals, highest value first. */
export const PRIORITY = FUSED
  .filter(f => f.quadrant === "both")
  .sort((a, b) => b.budget - a.budget);


// ─── Flood hazard ─────────────────────────────────────────────────────────────
// UP NOAH 100-year modelled flood extent, joined by point-in-polygon. For a
// flood-control register this asks the question the money is meant to answer.
//
// Read it with the distance, not without: 306 contracts sit outside the modelled
// extent but within a kilometre of it, which is where you build a revetment. Only
// 3 are further out — and all three already carry a coordinate flag, so this
// corroborates the records tier rather than finding anything new.

export interface HazardResult {
  id: string;
  hazard: "none" | "low" | "medium" | "high" | null;
  level: number | null;
  metresToHazard: number | null;
}
export interface HazardRun {
  generated: string;
  source: { name: string; dataset: string; file: string; url: string; crs: string; polygonParts: number };
  caveat: string;
  farThresholdMetres: number;
  tally: Record<string, number>;
  results: HazardResult[];
}
export const HAZARD = hazardRaw as unknown as HazardRun;
export const HAZARD_BY_ID = new Map(HAZARD.results.map(r => [r.id, r]));

/**
 * Year-by-year comparison.
 *
 * BetterGov's flood-control map (CC0, bettergovph/bettergov) has a "Projects by
 * Year" chart, and it is the right idea — this adopts it and adds the columns
 * their data cannot produce, because they plot the register rather than audit it.
 *
 * The reason it is worth showing: the round-number bidding pattern has a start
 * date. It is absent through 2018, appears at 3% in 2019, and jumps to 51% in
 * 2020 — where it stays. A yearly view is the only place that shows up.
 *
 * Reported as TWO series on two charts rather than one chart with two axes.
 * Value and percentage do not share a scale, and a dual-axis chart can be made
 * to show any relationship the author wants.
 */
export interface YearStat {
  year: number;
  projects: number;
  value: number;
  valueM: number;
  flagged: number;
  flaggedRate: number;
  at96: number;
  at96Rate: number;
  singleBidder: number;
  withRatio: number;
}

export const YEAR_STATS: YearStat[] = (() => {
  const years = [...new Set(PROJECTS.map(p => p.infraYear).filter((y): y is number => y != null))].sort();
  return years.map(year => {
    const g = PROJECTS.filter(p => p.infraYear === year);
    const ratios = g.map(p => PROC_BY_ID.get(p.id)?.bidRatio).filter((r): r is number => r != null);
    const at96 = ratios.filter(r => Math.abs(r * 100 - 96) < 0.01).length;
    const flagged = g.filter(p => p.auditFlags.length > 0).length;
    const value = g.reduce((s, p) => s + p.budget, 0);
    return {
      year, projects: g.length, value, valueM: Math.round(value / 1e6),
      flagged, flaggedRate: g.length ? flagged / g.length : 0,
      at96, at96Rate: ratios.length ? at96 / ratios.length : 0,
      singleBidder: g.filter(p => PROC_BY_ID.get(p.id)?.bidders === 1).length,
      withRatio: ratios.length,
    };
  });
})();
